baseurl = "https://www.monicailiu.com"
title = "monicaliu"
theme = "vec"
languageCode = "en-us"
paginate = 10
disqusShortname = "miliu"
googleAnalytics = "UA-57408564-1"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "portfolio"
    weight = 1
    url = "/portfolio"
  [[menu.main]]
    name = "contact"
    weight = 0
    url = "/contact"
  [[menu.main]]
    name = "faq"
    weight = 2
    url = "/faq"

[params]
  Keywords = "key, 关键字, キーワード"
  Description = "my personal site"
  Avatar = "img/avatar.jpg"
  SelfIntro = "Welcome to the land of Monica; a constant battle of passions between art and code"
  Email = "monicailiu@gmail.com"

  GithubID = "Your Github ID"
  TwitterID = "Your Twitter ID"
  FacebookID = "Your Facebook ID"
  LinkedInID = "Your LinkedIn ID"
  GoogleplusID = "Your Googleplus ID"
