baseurl = "https://www.monicailiu.com"
title = "monicaliu"
theme = "vec"
languageCode = "en-us"
paginate = 10
disqusShortname = "miliu"
googleAnalytics = "UA-57408564-1"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "resume"
    weight = 0
    url = "/resume"
  [[menu.main]]
    name = "portfolio"
    weight = 1
    url = "/portfolio"
  [[menu.main]]
    name = "contact"
    weight = 2
    url = "/contact"
    

[params]
  Keywords = "key, 关键字, キーワード"
  Description = "my personal site"
  Avatar = "img/mlenso.png"
  Email = "monicailiu1@gmail.com"

  GithubID = "monlu92"
  LinkedInID = "monicailiu"
