baseurl = "https://monicailiu.com"
title = "monicaliu"
theme = "vec"
languageCode = "en-us"
paginate = 10
disqusShortname = "miliu"
googleAnalytics = "UA-57408564-1"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "resume"
    weight = 0
    url = "/resume"
  [[menu.main]]
    name = "portfolio"
    weight = 1
    url = "/portfolio"
  [[menu.main]]
    name = "contact"
    weight = 2
    url = "/contact"
    

[params]
  Keywords = "key, 关键字, キーワード"
  Description = "my personal site"
  Avatar = "img/mlenso.png"
  Email = "monicailiu1@gmail.com"

  GithubID = "monlu92"
  LinkedInID = "monicailiu"

  AcrylicTiger = "img/art/tiger.png"
  AcrylicSuperman = "img/art/superman.png"
  AcrylicDeer = "img/art/deer.png"
  AcrylicBiggie = "img/art/biggie.jpg"
  OilGirl = "img/art/girl_oil.png"
  OilRose = "img/art/rose.png"
  PencilLeather = "img/art/leather_jacket.png"
  MarkerRhcp = "img/art/rhcp.png"
  PencilGirl = "img/art/girl_pencil.png"
  WoodGun = "img/art/gun.png"
  WoodMultiple = "img/art/wood.png"
